import turtle
screen= turtle.Screen()
screen.setup(400,400)
screen.bgcolor("purple")
board=turtle.Turtle()
board.forward(70)
board.left(60)
board.forward(70)
board.left(60)
board.forward(70)
board.left(60)
board.forward(70)
board.left(60)
board.forward(70)
board.left(60)
board.forward(70)
board.left(60)


turtle.done()